### ISSUE TITLE
The poll answer structure is difficult to maintain

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#116]
Currently each new poll answer is appended to the `poll_answers` object and it makes it difficult to read and maintain.

```json
  "poll_answers": [
    {
      "answers": [
        "1"
      ],
      "user": "desmos1e6sueymvr37p3qjztcacmrs0zd0yrkj5uzx7sa"
    },
    {
      "answers": [
        "1"
      ],
      "user": "desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u"
    }
  ],
```

It will be better if it shows in the structure ordered by the answers.

```json
  "poll_answers": {
       "1": [
                "desmos1e6sueymvr37p3qjztcacmrs0zd0yrkj5uzx7sa",
                "desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u"
        ],
        "2": [
                "..."
        ]
  },
```

**Comment by RiccardoM** [comment]
Answers are stored in the best possible way that later allows to verify a double-response or perform other checks. 

However, the transformation you require can be achieved in any programming language that allows for lists operators as follows: 

Javascript example:
```javascript
const flatten = data.flatMap((answer) => answer.answers.map((text) => [text, answer.user]));
const grouped = flatten.reduce(function (obj, item) {
  let key = item[0];
  let value = item[1];
  if (!obj[key]) {
    obj[key] = [value]; 
  } else {
    obj[key].push(value);
  }
  return obj;
}
```

Working example [here](https://jsbin.com/pasixatowe/edit?js,console). 

I would personally avoid changing how data is returned just to go towards the requirements of an app like in this case. Also because this will eventually be replaced by [Djuno](https://github.com/desmos-labs/djuno) which, combined with GraphQL, will allow applications to get the data the best way they desire

**Comment by RiccardoM** [comment]
What I can suggest is changing the returned data to flatten the `answers` inner array like so: 

```json
[
  {
    "value": "1",
    "user": "desmos1e6sueymvr37p3qjztcacmrs0zd0yrkj5uzx7sa"
  },
  {
    "value": "2",
    "user": "desmos1e6sueymvr37p3qjztcacmrs0zd0yrkj5uzx7sa"
  },
  {
    "value": "1",
    "user": "desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u"
  }
]
```

Instead of 

```
[
  {
    "answers": [
      "1",
      "2"
    ],
    "user": "desmos1e6sueymvr37p3qjztcacmrs0zd0yrkj5uzx7sa"
  },
  {
    "answers": [
      "1"
    ],
    "user": "desmos1fc3mdf0ue2f4suyg5vjj75jtaer0cl0dgqvy6u"
  }
]
```

This would allow for easier `filter`, `groupBy` and other operators usage. What do you think @kwunyeung?

**Comment by kwunyeung** [comment]
No need to change then. The flatten inner array looks fine but it turns out make the return data larger. If the current solution on storing structure and return result is the most efficient way, then just keep it. And let the frontend or middleware to organize the data for their purpose.
