### ISSUE TITLE
IBC-enabled social profile

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#192]
## Feature description 

The decentralized profile can serve as a central reference of a user profile. There is a pain point of validators and wallets. Validators are validating multiple chains. They have to setup their profiles in different chains every time. Every time they have to input their moniker, communication channels, bio, terms and conditions etc. The decentralized profile can serve as a reference to the validators, explorers and wallets can retrieve the profile directly from the decentralized profile. This also serve the users who are using the wallets if they would like to show extra profile information in their wallet. 

## Implementation proposal

The decentralized profile can be done by sending a signature from chain A to `DESMOS` via IBC sent by the profile owner account on `DESMOS`. Once the signature is verified, `DESMOS` will update a reference of the profile to the account on the chain A. We can then verify that the profile belongs to the address on chain A. The user on chain A should keep an open IBC channel between chain A and `DESMOS`. This will be considered the liveness of the profile of the user on chain A.

Superses #56

**Comment by RiccardoM** [comment]
I personally think that this feature is very interesting, and could lead Desmos to be the main repository for different profiles that can be used inside wallets, explorers and other dApps as well. 

That being said, I would like to expand the implementation proposal you have made, to make sure I understood it correctly before making any comment on it. 

What you have proposed is a system that works like this (for the sake of simplicity I will assume a Cosmos <-> Desmos communication): 

#### 1. Signature creation
First of all, Alice creates a signature object. Such object should be created as follows: 

```js
let firstSignature = sign(Alice.CosmosAddress, Alice.CosmosPrivKey)
let secondSignature = sign(firstSignature, Alice.DesmosPrivKey)
```

This way with a double signature we are verifying that Alice owns both the `cosmos1...` and `desmos1...` accounts.

#### 2. IBC packet creation
Once the signature has been created, an IBC packet will be formed. Such packet must contain: 

1. Alice's Desmos address in HEX form. 
2. Alice's Cosmos address in HEX form. 
3. Alice's Cosmos public key in HEX form.
4. The previously created `firstSignature` and `secondSignature` in HEX format. 


An example could be the following JSON packet: 

```json
{ 
  "source_address": "hex(Alice.CosmosAddress)",
  "source_pub_key": "hex(Alice.CosmosPubKey)",
  "destination_address": "hex(Alice.DesmosAddress)",
  "first_signature": "hex(<firstSignature>)",
  "second_signature": "hex(<secondSignature>)"
}
```

#### 3. IBC packet receving
Once the IBC packet has been transferred from the Cosmos chain to the Desmos chain, the following process should take place: 

1. Extract the data inside the packet:
   ```js
   let sourceAddress = hex_decode(packet.source_address)
   let sourcePubKey = hex_decode(packet.source_pub_key)
   let destinationAddress = hex_decode(packet.destination_address)
   let firstSignature = hex_decode(packet.first_signature)
   let secondSignature = hex_decode(packet.second_signature)
   ```

2. Verify the validity of the packet. This can be done by: 
   ```js
   // Verify the association between the public key and the address
   let addressFromPubKey = sourcePubKey.toAddress();
   assert(addressFromPubKey == sourceAddress);
   
   // Verify the signatures
   verify(secondSignature, firstSignature, Alice.DesmosPubKey)
   verify(firstSignature, sourceAddress, sourcePubKey)
   ```

3. Create a Desmos -> Cosmos accounts association.  


Is the depicted working correct @kwunyeung?

**Comment by bragaz** [comment]
This seems interesting and also not so difficult to implement. 
One thing for the point 3:
Is there a limit on the number of channels that an IBC-ready chain can handle? 
Otherwise I think we can also use a simple couple of IBC tx to declare the liveness of the profile on a certain chain.

**Comment by RiccardoM** [comment]
@bragaz I'd like to write here my considerations about the IBC channels thing as I've also said during our internal call yesterday morning. 

I do not think that requiring users to keep an active IBC channel is neither necessary nor a good practice for a couple of reasons. 

First of all, IBC channels can be opened by anyone, and when opened they can be used by anyone without permissions. That being said, if Alice opens a channel from Cosmos to Desmos, then Bob will be able to use that channel to setup hist account in any case. There will be no way to block Bob from being so. 

Second, keeping an IBC channel open requires constant transactions to be made. Channels have a finite expiration time (usually this will be 21 days), after which anyone needs to perform a transaction on both chains to keep them alive. This means that a constant monitoring process is required on IBC channels, which is a hard task that we cannot ask users to do. 

Last, but no least, IBC channels are thought to be agnostic from the data they allow to transport. Since they can be used by anyone (as specified earlier) we cannot do assumptions on the user that will use them. For example, we cannot assume that only Bob will keep alive and use his channel. For this reason, we cannot assume that an alive channel means an active user on the other chain.

**Comment by RiccardoM** [comment]
I would also like to explain further why I've thought  about the above implementation proposal. 

## The workings of IBC
### Packets
When to chains connected to each other want to communicate between them, they can do so by sending through a **channel** one or more **packets**.

Such packets are simply JSON objects that contain a list of specific data: 

- a sequence
- a source port
- a source channel
- a destination port
- a destination channel
- the **data** to be transfered
- the timeout height 
- the timeout timestamp

All these data are contained inside the CosmosSDK `Packet` structure.

### Packets data
Packets data can be any king of byte data. Usually they are obtained by serializing specific JSON objects that contain the data to be transferred from one chain to another.

As an example, the following represents the packet that is sent when a cross-chain token transfer is being made: 

```json
{
  "amount": {
    "denom": "<Coin denom>",
    "amount": "<Coin amount>"
  },
  "sender": "<Sender address>",
  "receiver": "<Receiver address>"
}
```

(Inside the Cosmos SDK this is represented by the `FungibleTokenPacketData` type). 

### Performing a cross-chain operation
When an operation (i.e. a token transfer) needs to be performed from one chain to another, the following operations are done: 

1. The **data** of the packet is created (i.e. `FungibleTokenPacketData`).
2. The data is serialized, and put inside a new `Packet` object.
3. Through the usage of a `ChannelKeeper`, the `Packet` is sent from the source chain to the destination chain. 
4. On the destination chain, the `Packet` is received. 
5. The packet is re-directed to the proper module by the IBC router. 
6. Inside the module, the `Packet` **data** is de-serialized and handled properly.

As you can see, there are some particularities that distinguish the packet sending from the transaction sending: 

#### 1. Packet data **are not signed**.  
This means that if a packet data contains the instruction of transferring some funds from Alice to Bob, it does not need to be signed from Alice nor Bob to be valid. Anyone can create such packet.

The fact that inside the Cosmos Hub the authorization is done thought the usage of a `MsgTransfer` transaction is just a precaution, but any module could create packets on behalf of any user.  

An example could be a module that allows Alice to withdraw money from Bob. Such module would simply create a `Packet` containing a new `FungibleTokenPacketData` instance with Bob as the sender and `Alice` as the receiver.

#### 2. Packets are not signed. 
Again, there is no way to verify that a specific `Packet` instance has been created from a specific user. 

Anyone can impersonate anyone, sending packets from the source chain and/or receiving them into the destination chain, without the involved users knowing it. 

An example could be again Alice sending some money to Bot, from the Cosmos chain into the Desmos chain. To do this, Alice can simply perform a transaction containing the `MsgTransfer` message. From this point on, it will be responsibility of one of the relayers between Cosmos and Desmos to effectively transfer the packet. Such relayers do not need to understand the contained data, and act as mere communication channels between the two chains transferring the data bakc and forth between them. 


## IBC implications for cross-chain profiles
Now that the workings of IBC is fully clear, as you can see there are two things that need to be considered when designing our integration with other chains. 

#### 1. We cannot assume the sender of a packet
Since packets are not signed, nor is the contained packet data, we **cannot assume the sender of a packet**. For this reason, we need to make sure that the packet sender is what he is telling everyone that is. 

That's why in my proposal I've included the first signature that can be later verified to be valid against the included source address. 

#### 2. We cannot assume the packet receiver
Since packets are received from generic relayers, we **cannot assume that the receiver will be the same user that has sent the packet itself**. For this reason, we need to make sure that during a profile connection, the user that effectively controls the source account (i.e. the Cosmos one) also controls the destination account (i.e. the Desmos one). 

That's why I've also included the second signature while creating the packet in my design. Otherwise Alice could simply connect her Cosmos account to the one of Bob, effectively stealing it without proving that she owns it. 

## Simplifications of my design
Know that I've explained the implications of IBC in cross-chain profiles, I would like to point out one things: there's a case on cross-chain profile creation that can simplify enormously the process. 

The real motivation behind the double signatures is that while thinking about that implementation I've thought about the case of a user that does not use the same mnemonic on each chain. This can for example be the case of validators, that for security reasons might want to have a different mnemonic per chain the validate, or particularly cautions users that might want a different mnemonic for each chain they hold some tokens on.

For this reason, if the two addresses (source and destination) have been generated from different mnemonic (i.e. private keys), the only way we can prove that the user owns both of those addresses is to require him to sign something with them (that's the motivation between the double signatures). 

That being said, there's the completely opposite case: a user that uses the **same mnemonic for all the chains** he validates or holds some tokens on. 

In this case, the cross-chain account connection can be simplified a lot. Since all the chains addresses are bytes, once you have an address HEX encoded, it is in fact immediate to get another chain account properly. 

To make this clear, suppose that Alice uses the same mnemonic everywhere and that she wants to connect her Cosmos account to her Desmos account. To do so, she can simply create a new packet data with the following data inside: 

```json
{ 
  "source_address": "Bech32 or Hex encoded address",
  "source_public_key": "<Hex encoded public key>",
  "signature": "<Hex encoded signature>"
}
```

Since the public key hex will also allow to generate the Desmos address properly, this method does not require the double signature to work. 

## Conclusions
I hope my explanation allows you @kwunyeung and @bragaz to fully understand the motivation behind the double signatures, the caveats of IBC and how we can work around them. 

If I find anything new on how this process can be simplified, I will let you know here.

**Comment by bragaz** [comment]
So basically, we could have like 1 packet containing the following data:
```
{ 
  "source_address": "hex(Alice.CosmosAddress)",
  "source_pub_key": "hex(Alice.CosmosPubKey)",
  "destination_address": "hex(Alice.DesmosAddress)",
  "first_signature": "hex(<firstSignature>)",
  "second_signature": "hex(<secondSignature>)"
}
```
In this one, `destination_address` and `second_signature` fields would be optional, used only if a user owns more than 1 mnemonic, right?

**Comment by RiccardoM** [comment]
@bragaz I think the best way to do it is to actually define two different packet data types: 

```golang
// IBCAccountConnectionPacketData represents the packet data that should be sent inside an IBC
// packet when the user wants to connect the SourceAddress present on this zone to the
// DestinationAddress present on the destination zone. 
// 
// TODO: Explain the signature creation procedure
type IBCAccountConnectionPacketData struct {
  SourceChainPrefix  string `json:"source_chain_prefix"` // Bech32 prefix of the source chain
  SourceAddress      string `json:"source_address"`      // Bech32-encoded address
  SourcePubKey       string `json:"source_pub_key"`      // Hex-encoded public key related to the address
  DestinationAddress string `json:"destination_address"` // Hex-encoded address
  FirstSignature     string `json:"first_signature"`     // Hex-encoded signature
  SecondSignature    string `json:"second_signature"`    // Hex-encoded signature
}

// IBCAccountLinkPacketData represents the packet data that should be sent inside an IBC packet
// when the user wants to simply link his SourceAddress account to the account that is linked
// on the receiving zone and that can be generated starting from the SourcePubKey.
// The signature value should be the SourceAddress signed with the private key associated with
// the given SourcePubKey.
type IBCAccountLinkPacketData struct {
  SourceChainPrefix string `json:"source_chain_prefix"` // Bech32 prefix for the source hain
  SourceAddress     string `json:"source_address"`      // Bech32-encoded address 
  SourcePubKey      string `json:"source_pub_key"`      // Hex-encoded public key
  Signature         string `json:"signature"`           // Hex-encoded signature
}
```

This way the handling of the two can be properly separated into smaller and easier-to-understand methods.
