### ISSUE TITLE
Magpie Session created and expiration should be replaced with block height

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#23]
The current demo is generating a created time and expiry time on each session. This can't be verified and not able to make consensus. It has to be changed to block height.

**Comment by RiccardoM** [comment]
As pointed out inside #32, I would suggest replacing all the time-related data with block heights. I think we should rename this issue an make it more generic so that it can refer to: 

- Post creation time
- Like creation times
- Session creation time
- Session expiration time

This should be pretty straightforward as we can user the `ctx.BlockHeight()` value that should be deterministic and coherent between all the nodes.
