### ISSUE TITLE
The error message is not user friendly

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#234]
This transaction was failed as the `DTag` has an ending space.

http://lcd.morpheus.desmos.network:1317/txs/9BEA99F5699EF59FC1183520F217D89B0DF16224C5BDC3B92C4993C7BF59C139

The error message is not user friendly as it directly mention the format of the RegEx.

```
invalid request: invalid profile dtag, it should match the following regEx ^[A-Za-z0-9_]+$: failed to execute message; message index: 0
```
I prefer the error message to be a sentence like `DTag only accepts alphabets and numbers without space`.

**Comment by RiccardoM** [comment]
@kwunyeung we changed to deliver this particular message due to the fact that actually the `DTag` validation regex is an on-chain parameter. This means that if one day the community decides that DTag can have spaces (or event other special characters), then such regex can be changed by an on-chain proposal. 

For this reason, we cannot return to the user the message you have suggested, since it would have to change if the regex changed.

**Comment by kwunyeung** [comment]
I see. That makes sense then.
