### ISSUE TITLE
Parametric session length 

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/desmos#38]
**Is your feature request related to a problem? Please describe.**
Currently with PR #37 we've switched from using `time.Time` values to `int64` when representing the duration time of `magpie` sessions. 

Taken from @kwunyeung's https://github.com/desmos-labs/desmos/pull/37#discussion_r343842132 we should think about having a parametric session duration time. 

**Describe the solution you'd like**
I suggest leaving the user the ability to specify a session length (in blocks) when creating it. This could be done by adding a new `duration` parameter to the `MsgCreateSession` type. 

I would also like to know more about what @kwunyeung meant with "We should add this to the Genesis params later" in order to know if we can implement such thing.

**Comment by RiccardoM** [comment]
@kwunyeung Can I please have your explanation of the following tip? 

> We should add this to the Genesis params later

I would like to dig a little bit more deeper into this issue to know if we still need to implement it or not.

**Comment by kwunyeung** [comment]
@RiccardoM I was referring to having the duration parameter in genesis file. 

I think letting the user to set their own session duration is dangerous because it can expire a long time later without interacting with the chain. The assumption under session is that the user broadcasting message to the chain is from the same person within that comparably short duration. I would prefer we verify it again after that duration and it's not desirable if the user can change this duration on their own.

**Comment by RiccardoM** [comment]
@kwunyeung It makes sense and I agree with your solution of **not** allowing users to specify a duration but, instead, putting the default value only inside the genesis file.

**Comment by kwunyeung** [comment]
Good! Let's put the value in the genesis file then.
