### ISSUE TITLE
`EndBlocker` `subspaces` checks

### ISSUE THREAD

**Issue by bragaz** [desmos-labs/desmos#488]
With the addition of the `subspaces` module, `profiles` (and maybe `posts`) could need some specific checks that runs automatically in their `EndBlocker`s to ensure if users involved in operations like `relationships` or `blocks` 
are still registered in those `subspaces` where the operations are performed and, in case they're not, manage it.
The implementation shouldn't be difficult and I will take care of post here a proposal in the following days.
Thoughts on this? @RiccardoM @dadamu

**Comment by RiccardoM** [comment]
I think this is worth exploring. However, we should try to implement this as efficiently as possible. For this reason, I think we should only consider the users that have unregistered from a subspace. We should **not** delete relationships or other things related to banned users, since they might always be unbanned in the future. 

I think the most efficient implementation would then be to: 
1. When a user unregisters from a subspace, store the `(user + suspace)` pair in a list. 
2. At each `EndBlock`, run through the list of unregistered users and delete everything related to them. 

Since we are going to have queries that allow us to get the information of a user for a given subspace in O(1) time, this should be pretty easy to do. Also, it should avoid having to iterate over all the users to see if they are unregistered. We simply store the unregistered ones and use that information to clear the store.

**Comment by RiccardoM** [comment]
Closing this as it will be discussed better when we implement the ADR for the `x/posts` module
