### ISSUE TITLE
Add command to generate chain link file

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#572]
## Feature description 

Currently, the `sign` cmd returns the hex-ecoded public key. However, The public key in the proof object is required as base64-encoded string when creating a chain link. From my side, the `sign` cmd should return the public key as base64-encoded.

The chain link required file:
```json
{
   "address":{
      "@type":"/desmos.profiles.v1beta1.Bech32Address",
      "value":"cosmos15uc89vnzufu5kuhhsxdkltt38zfx8vcyggzwfm",
      "prefix":"cosmos"
   },
   "proof":{
      "pub_key":{
         "@type":"/cosmos.crypto.secp256k1.PubKey",
         "key":"A58DXR/lXKVkIjLofXgST/OHi+pkOQbVIiOjnTy7Zoqo"   /*<- It's base64-encoded*/
      },
      "signature":"ecc6175e730917fb289d3a9f4e49a5630a44b42d972f481342f540e09def2ec5169780d85c4e060d52cc3ffb3d677745a4d56cd385760735bc6db0f1816713be",
      "plain_text":"cosmos15uc89vnzufu5kuhhsxdkltt38zfx8vcyggzwfm"
   },
   "chain_config":{
      "name":"cosmos"
   }
}
```

## Implementation proposal

Let the public key of signature data in `sign` cmd be base64-encoded.

**Comment by RiccardoM** [comment]
@dadamu Where is the Base64-encoded public key used from? I've searched the code and did not find a single usage of the `base64` package, a part from the tests of the application links (due to the fact that Band uses it)

**Comment by RiccardoM** [comment]
@dadamu The `sign` command returns an hex-encoded signature and public key because it should be used when creating **application** links. The process should be: 
1. The user signs its application username using the `sign` command.
2. The returned output is posted online. 
3. The Band data sources will fetch and validate those data expecting an hex-encoded signature and public key. 

Changing this command would break everything. 

Also, I don't think it's worth changing it and requiring the user to create the chain-link object by themselves. Instead, what we should do is create a new command that allows the user to create such object easily. However, I think this is not a priority right now since the overall JSON object can be created very easily using Protobuf and the JSON encoding of the Cosmos-provided objects. Indeed, the public key value is simply obtained by creating a `cryptotypes.PubKey` instance and encoding it with the `json` package.

**Comment by dadamu** [comment]
@RiccardoM Okay, I am thinking about the same thing that creating a new command in order to generate object easily.
Currently, to have a chain link, the user should use `sign` command to generate the signature and get base64-encoded public key, then create the such object manually.
I suppose it should be mentioned in docs before the command is out.
