### ISSUE TITLE
Some new posts can't be created with the same invalid error message

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/desmos#64]
These txs are all failed and have error message with the same `Post ID` 17.

`828D4A5EE5488F1B1C67CC72410B2F62CEF7A67DFB4F6EF2CE1FA550136DCDF0`
`4951F960C4A8D222175D377138D1B9519A79FC609E6410B03C71361067FF4BEC`
`6FB74064F5038995FB1DF9FFA246C96B1AF5A5D3DD4A1F452DC5AA299C877809`
`CAEB1E82282EE31F5CAE3D3E99838DBD62064142C90C480CF29976917A88742E`
` D262923277A6FD586A40289E3BFB7D5067FAE1335A9B6652B1CF5B8A8A77C9C2`

Their error messages are all

```
"{\"codespace\":\"sdk\",\"code\":6,\"message\":\"Post with id 17 already exists\"}"
```

**Comment by bragaz** [comment]
Ok it is an issue that occurred after the first ever message’s edit.
In particular the editing of message with **ID == 16**, made in tx with `txHash` = `0900361423873B5B335887099C334AD005A4BEDF3B6FD61F1FC4B775D4DDC46A`.
What’s happening here is the following situation:
1) A user edits his/her own post, when this post it’s going to be saved, the LastPostID is set to the current edited post’s one, in our case: 16.
2) After that, everyone who tries to create a new post will get the error `Post with id 17 already exists` because of the assignment.
So this is a problem about how we currently handle posts ID and in particular with the way we set the ID to latest post inside `handleMsgCreatePost` .

**Comment by bragaz** [comment]
Since I can't push my solution, I'll wrote it down here:
Adding a check to make sure that the current post we are saving is a new one and not an edited one.
```golang
// Set the last post id
if post.LastEdited == sdk.ZeroInt() {
    store.Set([]byte(types.LastPostIDStoreKey), k.Cdc.MustMarshalBinaryBare(&post.PostID))
}
```
I think this will be enough, hope it's correct!
