### ISSUE TITLE
Split the links features from `x/profiles`

### ISSUE THREAD

**Issue by dadamu** [desmos-labs/desmos#775]
## Feature description 

As the same as `x/relationships`, I suggest splitting chain-link and application-link to a a independent module from `x/profiles`. It would improve the maintainability by having smaller code base in each modules.

What do you think? @bragaz @RiccardoM

**Comment by RiccardoM** [comment]
Honestly, I don't think we should split the links away from the `x/profiles` module. 

The reasons behind splitting the `x/relationships` away were mainly two: 
1. it shouldn't be necessary for users to have a profile in order to have a relationships between them (I should be able to follow someone even if I'm an outsider)
2. if those features would have been left there, it would have required the `x/profiles` and `x/subspaces` module to have a dependency circle. Instead, this way we can have the following: 
   ```
   relationships
       /      \
   profiles  subspaces
   ```


I believe app and chain links should stay inside the `x/profiles` module as they are very tightly coupled with profiles themselves: it shouldn't be allowed to have a link without having a profile

**Comment by dadamu** [comment]
@RiccardoM 
Just have a dump question. Why do chain links and app links should require a profile? IMO, both profile and link could be independent thing.

**Comment by RiccardoM** [comment]
@dadamu That's due to the idea of "decentralized identity": you create a single identity and connect other chains to it. And then you use application links to verify that's really you. I think it makes sense that a profile is required for chain links and application links to be created as well. 

On the other hand, I believe relationships should also exist between people that do not have a profile. I would like to know @kwunyeung and @bragaz idea though, we might want to bring back the requirement of having a profile to follow/be followed if you guys think it's best that way.

**Comment by bragaz** [comment]
@RiccardoM @dadamu The whole concept of the Desmos Profile unwraps around the possibility to verify that it belongs to you by linking it to other chains and services like centralised apps. It's true that we can do the same by connecting the wallet directly but I would avoid doing this due to the fact that this will make the profile worthless to have since once you've verified it, a client can build its own profile on the top of it. And this will lead to different kind of profiles in clients loosing the de-facto standard Desmos Profile narrative.

About the relationships, I don't think we mandatory to have profile to create them, since they can also be used by wallets as a sort of decentralised address book.

**Comment by dadamu** [comment]
@RiccardoM @bragaz 
From my side, profile provides name service with dtag. Those who want to have a dtag as name service would create a profile, meaning that profile is still worth without links. 
The function of link is actually giving a proof between the wallet and an external address. Splitting links from profile gives more one option to the user, and doesn't affect the function of profile.

But sure, with current narrative of Profile, links should be based on Profile.

**Comment by kwunyeung** [comment]
I don’t think splitting the modules would make sense. The idea of the `decentralized identity` is for users to form their social profiles by linking their wallets from different chains and applications which show their activities and asset ownership. Without a profile, it becomes meaningless to connect different wallets. This also explains that a *profile* is not just a handle or username.

I also agree with @RiccardoM on the requirement of having a profile to follow/be followed.
